Repository Xtao-Labs/PagerMaid-Modify, pull requests merged in 2021-04, with the labels that each got.

#54 📈 使用 Sentry 统计用户报错
  pagermaid/__init__.py
  pagermaid/listener.py
  requirements.txt
Labels: enhancement

#55 🐛 修复 block bot 后的报错问题
  pagermaid/utils.py
Labels: bug

#56 📈 优化 sentry
  pagermaid/__init__.py
  pagermaid/__main__.py
  pagermaid/utils.py
Labels: bug, enhancement

#57 🐛 修复中英字符错误
  pagermaid/utils.py
Labels: bug, enhancement

#58 🐛 修复 Sentry 发送多余错误
  pagermaid/__init__.py
  pagermaid/utils.py
Labels: bug

#59 ✨ speedtest 支持图片凡尔赛
  plugins/status.py
Labels: enhancement

#60 I18n
  .gitignore
  languages/built-in/en.yml
  languages/built-in/zh-cn.yml
  pagermaid/__init__.py
  pagermaid/__main__.py
  pagermaid/listener.py
  pagermaid/modules/__init__.py
  pagermaid/modules/account.py
  pagermaid/modules/avoid.py
  pagermaid/modules/captions.py
  pagermaid/modules/clock.py
  pagermaid/modules/external.py
  pagermaid/modules/fun.py
  pagermaid/modules/help.py
  pagermaid/modules/message.py
  pagermaid/modules/plugin.py
  pagermaid/modules/prune.py
  pagermaid/modules/qr.py
  pagermaid/modules/status.py
  pagermaid/modules/sticker.py
  pagermaid/modules/system.py
  pagermaid/modules/update.py
  pagermaid/utils.py
  plugins/README
Labels: enhancement

#61 🐛 Fix docker automatic update
  Dockerfile
  Dockerfile.persistant
  pagermaid/modules/update.py
Labels: bug

#63 💚 Docker support more version
  Dockerfile
  Dockerfile.persistant
  docker-compose.gen.yml
  utils/docker-run.sh
Labels: enhancement

#64 👷 Fix docker automatic update
  Dockerfile
  docker-compose.gen.yml
  utils/docker-run.sh
Labels: bug

#67 🐛📝 Fix speedtest error and add new translations
  languages/built-in/en.yml
  languages/built-in/zh-cn.yml
  languages/built-in/zh-tw.yml
  pagermaid/__init__.py
  pagermaid/modules/status.py
Labels: bug, documentation
