Repository Xtao-Labs/PagerMaid-Modify, pull requests merged in 2021-12, with the labels that each got.

#152 🐛 Fix sb and ship error
  pagermaid/modules/fun.py
  pagermaid/modules/sb.py
Labels: bug, PR: awaiting review, PR: author is committer

#153 ✨ Support ban channel
  languages/built-in/en.yml
  languages/built-in/zh-cn.yml
  languages/built-in/zh-tw.yml
  pagermaid/modules/sb.py
Labels: enhancement, PR: awaiting review, PR: author is committer

#154 ✨ Fix repeat command forward error
  pagermaid/modules/message.py
Labels: PR: awaiting review

#155 🐛 Fix the problem that `s to` command cannot ignore emoji.
  pagermaid/modules/sticker.py
Labels: bug, PR: awaiting review, PR: author is committer

#157 Update install.sh[修复没有开启二次验证情况下出现的死循环]
  install.sh
Labels: PR: awaiting review, PR: first-time contributor

#158 ✨ Support auto install extra pypi packages.
  .gitignore
  pagermaid/__init__.py
  pagermaid/utils.py
Labels: enhancement, PR: awaiting review, PR: author is committer

#161 🐛 Fix sb cannot recognize formatted text and add support MessageMediaUnsupported for s.
  pagermaid/modules/sb.py
  pagermaid/modules/sticker.py
Labels: bug, PR: awaiting review, PR: author is committer
