Repository Xtao-Labs/PagerMaid-Modify, pull requests merged in 2021-06, with the labels that each got.

#84 🐛Fixed the problem that the plugin does not exist.
  pagermaid/__init__.py
  pagermaid/modules/plugin.py
  requirements.txt
Labels: bug

#87 🐛 fix speedtest image error, apt install error.
  pagermaid/modules/plugin.py
  pagermaid/modules/status.py
Labels: bug

#88 ✨ support set alias for the command.
  languages/built-in/en.yml
  languages/built-in/zh-cn.yml
  languages/built-in/zh-tw.yml
  pagermaid/__init__.py
  pagermaid/modules/account.py
  pagermaid/modules/avoid.py
  pagermaid/modules/captions.py
  pagermaid/modules/clock.py
  pagermaid/modules/external.py
  pagermaid/modules/fun.py
  pagermaid/modules/help.py
  pagermaid/modules/message.py
  pagermaid/modules/plugin.py
  pagermaid/modules/prune.py
  pagermaid/modules/qr.py
  pagermaid/modules/status.py
  pagermaid/modules/sticker.py
  pagermaid/modules/system.py
  pagermaid/modules/update.py
  pagermaid/utils.py
Labels: enhancement

#89 ✨⚡️ Selfprune support reply, add eval Python exec,import sticker performance.
  languages/built-in/en.yml
  languages/built-in/zh-cn.yml
  languages/built-in/zh-tw.yml
  pagermaid/modules/prune.py
  pagermaid/modules/system.py
  pagermaid/modules/update.py
Labels: enhancement

#90 🐛 Fixed docker not support pingdc, fixed update error.
  Dockerfile
  pagermaid/modules/update.py
Labels: bug

#91 🐛 Fix a lot of bugs.
  pagermaid/__init__.py
  pagermaid/modules/account.py
  pagermaid/modules/captions.py
  pagermaid/modules/external.py
  pagermaid/modules/message.py
  pagermaid/modules/status.py
  pagermaid/modules/sticker.py
  pagermaid/modules/update.py
Labels: bug

#92 🐛 Fix a lot of bugs.
  pagermaid/__init__.py
  pagermaid/modules/fun.py
Labels: bug

#93 ✨ Support http proxy
  config.gen.yml
  pagermaid/__init__.py
  requirements.txt
Labels: dependencies, enhancement

#95 ✨🐛 Support custom APT source,fixed some bugs.
  config.gen.yml
  pagermaid/__init__.py
  pagermaid/modules/plugin.py
  pagermaid/modules/sticker.py
Labels: bug, enhancement

#96 修正docker-composep安装教程
  utils/docker.md
Labels: documentation
