Repository Xtao-Labs/PagerMaid-Modify, pull requests merged in 2021-02, with the labels that each got.

#48 🐛 修复 -id 无法在私聊中使用的问题
  README.md
  pagermaid/modules/message.py
Labels: PR: author is committer, PR: awaiting review, bug

#50 新增 apt 批量安装
  pagermaid/modules/plugin.py
Labels: PR: awaiting review, enhancement

#51 🐛 增加 Sticker 命令的适用场景
  pagermaid/modules/sticker.py
Labels: PR: awaiting review, bug

#52 config.ini 更新
  config.gen.ini
Labels: PR: awaiting review, bug
