Repository Xtao-Labs/PagerMaid-Modify, pull requests merged in 2021-09, with the labels that each got.

#128 🐛🚀 fix some bugs and support for deploy to railway
  README.md
  pagermaid/__init__.py
  pagermaid/interface/__init__.py
  pagermaid/modules/external.py
  pagermaid/modules/sb.py
  pagermaid/modules/sticker.py
  pagermaid/static/images/icon.jpg
  pagermaid/templates/includes/navbar.html
  utils/gensession.py
Labels: bug, enhancement, PR: awaiting review, PR: author is committer

#129 🐛⚡️ fix double log and add uptime
  config.gen.yml
  languages/built-in/en.yml
  languages/built-in/zh-cn.yml
  languages/built-in/zh-tw.yml
  pagermaid/__init__.py
  pagermaid/interface/__init__.py
  pagermaid/modules/clock.py
  pagermaid/modules/status.py
Labels: bug, enhancement, PR: awaiting review, PR: author is committer

#130 🐛 fix some bugs
  pagermaid/__init__.py
  pagermaid/interface/__init__.py
  pagermaid/modules/fun.py
  pagermaid/modules/message.py
Labels: bug, PR: awaiting review, PR: author is committer

#132 🐛 Fix PhotoInvalidDimensionsError
  languages/built-in/en.yml
  languages/built-in/zh-cn.yml
  languages/built-in/zh-tw.yml
  pagermaid/modules/captions.py
Labels: bug, PR: awaiting review, PR: author is committer

#133 🐛⬆️ Fix user doesn't exist and update sentry version.
  pagermaid/listener.py
  pagermaid/modules/account.py
  pagermaid/modules/avoid.py
  pagermaid/modules/message.py
  requirements.txt
Labels: bug, PR: awaiting review, PR: author is committer, dependencies

#134 应群友需求，增加一并删除对方消息功能
  pagermaid/modules/sb.py
Labels: enhancement, PR: awaiting review, PR: first-time contributor
