Repository Xtao-Labs/PagerMaid-Modify, pull requests merged in 2021-11, with the labels that each got.

#145 对贴纸指令添加新格式
  pagermaid/modules/sticker.py
Labels: enhancement, PR: awaiting review

#144 性能优化 + `block`, `unblock` 指令优化
  pagermaid/__init__.py
  pagermaid/modules/account.py
Labels: bug, PR: awaiting review

#146 🐛 fix some bugs
  pagermaid/modules/account.py
  pagermaid/modules/captions.py
  pagermaid/modules/message.py
Labels: bug, PR: awaiting review, PR: author is committer

#147 Update install.sh
  install.sh
Labels: PR: awaiting review

#148 Use aiohttp to accelerate network requests and Support silent mode and fix some bugs.
  .github/ISSUE_TEMPLATE/bug_report_en.md
  .github/ISSUE_TEMPLATE/bug_report_zh.md
  .github/ISSUE_TEMPLATE/feature_request_en.md
  .github/ISSUE_TEMPLATE/feature_request_zh.md
  INSTALL.md
  README.md
  config.gen.yml
  install.sh
  languages/built-in/en.yml
  languages/built-in/zh-cn.yml
  languages/built-in/zh-tw.yml
  pagermaid/__init__.py
  pagermaid/bots/message.py
  pagermaid/bots/status.py
  pagermaid/bots/update.py
  pagermaid/modules/account.py
  pagermaid/modules/captions.py
  pagermaid/modules/external.py
  pagermaid/modules/fun.py
  pagermaid/modules/message.py
  pagermaid/modules/plugin.py
  pagermaid/modules/prune.py
  pagermaid/modules/qr.py
  pagermaid/modules/status.py
  pagermaid/modules/sticker.py
  pagermaid/modules/system.py
  pagermaid/modules/update.py
  pagermaid/utils.py
  requirements.txt
  setup.py
Labels: bug, enhancement, PR: awaiting review, PR: author is committer

#149 🐛 Fix a bug by aiohttp.
  pagermaid/modules/plugin.py
  pagermaid/modules/status.py
  pagermaid/utils.py
Labels: bug, PR: awaiting review, PR: author is committer
