Repository Xtao-Labs/PagerMaid-Modify, pull requests merged in 2021-01, with the labels that each got.

#39 📝 对接 bot ，修改 issue 模板。
  .github/ISSUE_TEMPLATE/bug_report_en.md
  .github/ISSUE_TEMPLATE/bug_report_zh.md
  .github/ISSUE_TEMPLATE/feature_request_en.md
  .github/ISSUE_TEMPLATE/feature_request_zh.md
Labels: PR: author is committer, PR: awaiting review, documentation

#41 我也不知道起什么标题（
  install.sh
Labels: PR: author is committer, PR: awaiting review

#42 💩 一键脚本修锅
  install.sh
Labels: PR: author is committer, PR: awaiting review

#44 ✨ apt 支持一键更新、关闭 debug
  pagermaid/__init__.py
  pagermaid/modules/plugin.py
Labels: PR: author is committer, PR: awaiting review, enhancement

#45 🚑 修复致命日志加载错误
  pagermaid/__init__.py
Labels: PR: author is committer, PR: awaiting review, bug
