Repository Xtao-Labs/PagerMaid-Modify, pull requests merged in 2021-07, with the labels that each got.

#100 🐛✏️ fix some public bugs, make update read path correctly.
  pagermaid/__init__.py
  pagermaid/modules/captions.py
  pagermaid/modules/fun.py
  pagermaid/modules/prune.py
  pagermaid/modules/status.py
  pagermaid/modules/update.py
Labels: bug

#104 ✨ Add an update reminder function.
  config.gen.yml
  languages/built-in/en.yml
  languages/built-in/zh-cn.yml
  languages/built-in/zh-tw.yml
  pagermaid/modules/update.py
Labels: enhancement

#105 ✨🐛 fix some bugs, add sb function to achieve cross-group ban.
  languages/built-in/en.yml
  languages/built-in/zh-cn.yml
  languages/built-in/zh-tw.yml
  pagermaid/__init__.py
  pagermaid/modules/message.py
  pagermaid/modules/sb.py
Labels: bug, enhancement

#106 📝 Update install.sh and Reduce update notification frequency.
  install.sh
  pagermaid/modules/update.py
Labels: bug

#107 ⚡️ Enable users to customize update alerts.
  config.gen.yml
  pagermaid/modules/update.py
Labels: enhancement

#108 📈 Add user Experience Program.
  config.gen.yml
  pagermaid/__init__.py
  pagermaid/listener.py
  requirements.txt
Labels: dependencies, enhancement

#109 ✨🐛📈 Support sticker set search, fix a analytic bug.
  languages/built-in/en.yml
  languages/built-in/zh-cn.yml
  languages/built-in/zh-tw.yml
  pagermaid/listener.py
  pagermaid/modules/message.py
  pagermaid/modules/sticker.py
  requirements.txt
Labels: bug, dependencies, enhancement

#110 🐛📈 Fix the problem of unlimited restart.
  pagermaid/__init__.py
Labels: bug

#111 ⚡️📈 Help network bad areas access analytics API.
  config.gen.yml
  pagermaid/__init__.py
  pagermaid/listener.py
  requirements.txt
Labels: bug, dependencies

#112 ✨ Support for export plug-in list for fast migration.
  languages/built-in/en.yml
  languages/built-in/zh-cn.yml
  languages/built-in/zh-tw.yml
  pagermaid/modules/plugin.py
Labels: enhancement

#113 ✨ Support official CLI to run speedtest.
  config.gen.yml
  pagermaid/modules/status.py
Labels: enhancement
